const SHOW_SUCCESS_ALERT = "SHOW_SUCCESS_ALERT";
const HIDE_SUCCESS_ALERT = "HIDE_SUCCESS_ALERT";
const SHOW_DANGER_ALERT = "SHOW_DANGER_ALERT";
const HIDE_DANGER_ALERT = "HIDE_DANGER_ALERT";
const UPDATE_USER_ACCOUNT_DATA = "UPDATE_USER_ACCOUNT_DATA";
const UPDATE_ERROR = "UPDATE_ERROR";
const UPDATE_SUCCESS = "UPDATE_SUCCESS";
const SHOW_SPINNER = "SHOW_SPINNER";
const HIDE_SPINNER = "HIDE_SPINNER";
const SHOW_IDENTITY_CONFIRMATION_FORM = "SHOW_IDENTITY_CONFIRMATION_FORM";
const HIDE_IDENTITY_CONFIRMATION_FORM = "HIDE_IDENTITY_CONFIRMATION_FORM";
const SET_REGISTRATIONS = "SET_REGISTRATIONS";
const SHOW_ADD_REGISTRATION_FORM = "SHOW_ADD_REGISTRATION_FORM";
const HIDE_ADD_REGISTRATION_FORM = "HIDE_ADD_REGISTRATION_FORM";
const CLEAR_ADD_REGISTRATION_FORM_ROLES = "CLEAR_ADD_REGISTRATION_FORM_ROLES";
const PUSH_ADD_REGISTRATION_FORM_ROLE = "PUSH_ADD_REGISTRATION_FORM_ROLE";
const POP_ADD_REGISTRATION_FORM_ROLE = "POP_ADD_REGISTRATION_FORM_ROLE";
const SET_ROLES = "SET_ROLES";
const UPDATE_ADD_REGISTRATION_FORM_FACULTY_IDENTITY = "UPDATE_ADD_REGISTRATION_FORM_FACULTY_IDENTITY";
const UPDATE_ADD_REGISTRATION_FORM_FACULTY_STATUSES = "UPDATE_ADD_REGISTRATION_FORM_FACULTY_STATUSES";

export {
  SHOW_SUCCESS_ALERT,
  HIDE_SUCCESS_ALERT,
  SHOW_DANGER_ALERT,
  HIDE_DANGER_ALERT,
  UPDATE_SUCCESS,
  UPDATE_USER_ACCOUNT_DATA,
  UPDATE_ERROR,
  SHOW_SPINNER,
  HIDE_SPINNER,
  SHOW_IDENTITY_CONFIRMATION_FORM,
  HIDE_IDENTITY_CONFIRMATION_FORM,
  SET_REGISTRATIONS,
  SHOW_ADD_REGISTRATION_FORM,
  HIDE_ADD_REGISTRATION_FORM,
  CLEAR_ADD_REGISTRATION_FORM_ROLES,
  PUSH_ADD_REGISTRATION_FORM_ROLE,
  POP_ADD_REGISTRATION_FORM_ROLE,
  SET_ROLES,
  UPDATE_ADD_REGISTRATION_FORM_FACULTY_IDENTITY,
  UPDATE_ADD_REGISTRATION_FORM_FACULTY_STATUSES
}
