const SHOW_SUCCESS_ALERT = "SHOW_SUCCESS_ALERT";
const HIDE_SUCCESS_ALERT = "HIDE_SUCCESS_ALERT";
const SHOW_DANGER_ALERT = "SHOW_DANGER_ALERT";
const HIDE_DANGER_ALERT = "HIDE_DANGER_ALERT";
const UPDATE_USER_ACCOUNT_DATA = "UPDATE_USER_ACCOUNT_DATA";
const UPDATE_ERROR = "UPDATE_ERROR";
const UPDATE_SUCCESS = "UPDATE_SUCCESS";
const SHOW_SPINNER = "SHOW_SPINNER";
const HIDE_SPINNER = "HIDE_SPINNER";
const SHOW_IDENTITY_CONFIRMATION_FORM = "SHOW_IDENTITY_CONFIRMATION_FORM";
const HIDE_IDENTITY_CONFIRMATION_FORM = "HIDE_IDENTITY_CONFIRMATION_FORM";

export {
  SHOW_SUCCESS_ALERT,
  HIDE_SUCCESS_ALERT,
  SHOW_DANGER_ALERT,
  HIDE_DANGER_ALERT,
  UPDATE_SUCCESS,
  UPDATE_USER_ACCOUNT_DATA,
  UPDATE_ERROR,
  SHOW_SPINNER,
  HIDE_SPINNER,
  SHOW_IDENTITY_CONFIRMATION_FORM,
  HIDE_IDENTITY_CONFIRMATION_FORM
}
